### ISSUE TITLE
error when build with Visual studio 2015 + python 3.5

### ISSUE THREAD

**Issue by cbogithub** [dlitz/pycrypto#167]
src/libtom/tomcrypt_cfg.h(26): warning C4273: 'malloc': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_malloc.h(97): note: see previous definition of 'malloc'
src/libtom/tomcrypt_cfg.h(27): warning C4273: 'realloc': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_malloc.h(116): note: see previous definition of 'realloc'
src/libtom/tomcrypt_cfg.h(28): warning C4273: 'calloc': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_malloc.h(62): note: see previous definition of 'calloc'
src/libtom/tomcrypt_cfg.h(29): warning C4273: 'free': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_malloc.h(85): note: see previous definition of 'free'
src/libtom/tomcrypt_cfg.h(31): warning C4273: 'qsort': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_search.h(53): note: see previous definition of 'qsort'
src/libtom/tomcrypt_cfg.h(35): warning C4273: 'clock': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(137): note: see previous definition of 'clock'
src/libtom/tomcrypt_cipher.h(546): error C2133: 'cipher_descriptor': unknown size
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

**Comment by nitetrain8** [comment]
I found solutions to both of these issues. 

To fix the warnings, edit "tomcrypt.h" to define LTC_NO_PROTOTYPES before including "tomcrypt_cfg.h". 

To fix the error, edit line 546 of "tomcrypt_cypher.h" to remove "cipher_descriptor[]". This variable doesn't seem to be declared, used, or otherwise exist outside of the header here, and pycrypto passed the full test suite after being compiled with these changes.

As an aside, to run the test suite from setup.py, you need to modify it in two locations to add "if __name__ == "__main__"" guards around calls to disutils.core.setup().

Otherwise, SelfTests.Random.test__UserFriendlyRNG.RNGMultiprocessingForkTest will fail with a RuntimeError.

**Comment by MartyMacGyver** [comment]
Note that this is a similar problem for Python 2.7 builds of this package, with the same repair process.

**Comment by jakirkham** [comment]
I have added PR ( https://github.com/dlitz/pycrypto/pull/199 ) and PR ( https://github.com/dlitz/pycrypto/pull/200 ), which I believe address these issues. Please take a look and let me know what you think.
